# Generated by Django 4.2.10 on 2024-11-18 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoMySQL', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
